#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
launch_on_boot=$YNH_APP_ARG_LAUNCH_ON_BOOT
open_webserver_port=$YNH_APP_ARG_OPEN_WEBSERVER_PORT

#=================================================
# GLOBAL VARS
#=================================================
final_path=/var/www/$app


test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path "$path_url")

# Check web path availability
ynh_webpath_available "$domain" "$path_url"

# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path_url"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_app_setting_set "$app" domain "$domain"
ynh_app_setting_set "$app" path_url "$path_url"
ynh_app_setting_set "$app" final_path "$final_path"
ynh_app_setting_set "$app" launch_on_boot "$launch_on_boot"
ynh_app_setting_set "$app" open_webserver_port "$open_webserver_port"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

### Use these lines if you have to open a port for the application
### `ynh_find_port` will find the first available port starting from the given port.
### If you're not using these lines:
###		- Remove the section "CLOSE A PORT" in the remove script

# Find a free port
port=$(ynh_find_port 8095)
# Open this port
yunohost firewall allow --no-upnp TCP $port 2>&1
ynh_app_setting_set $app port $port

#=================================================
# CREATE EMBY USER
#=================================================
ynh_system_user_create "$app"

#=================================================
# ADD SYSTEMD CONFIG
#=================================================
ynh_add_systemd_config

if [ "$launch_on_boot" -eq 0 ]
then
    sudo systemctl disable "$app"
fi

#=================================================
# INSTALL EMBY
#=================================================
sudo cp ../conf/emby.list "/etc/apt/sources.list.d/${app}.list"
#sudo wget -nv https://download.opensuse.org/repositories/home:emby/Debian_9.0/Release.key -O Release.key
#sudo apt-key add - < Release.key
ynh_package_update
yunohost_package_install $app

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================
yunohost service add "$app" --log "$final_path/logs/emby.log"

#=================================================
# NGINX
#=================================================
finalnginxconf="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup_if_checksum_is_different "$finalnginxconf"
sudo cp ../conf/nginx.conf "$finalnginxconf"

if [ "$path_url" == "/" ]; then
    ynh_replace_string "__PATH__/" "/" "$finalnginxconf"
else
    ynh_replace_string "__PATH__" "$path_url" "$finalnginxconf"
fi

ynh_app_setting_set "$app" protected_uris "/"

domainregex=$(echo "$domain" | sed 's/-/\%&/g')
ynh_app_setting_set "$app" skipped_regex "$domainregex/jsonrpc.*$,$domainregex/image.*$"

# Reload SSOwat config
yunohost app ssowatconf

# Reload Nginx
systemctl reload nginx

#=================================================
# START EMBY
#=================================================
sudo systemctl start "$app"
